# Fase 1: Build con Maven y Java 17
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Fase 2: Imagen final con Java 17 (Render compatible)
FROM eclipse-temurin:17-jdk
WORKDIR /app

# COPIAR EL JAR CORRECTO
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]